# Generated by Django 3.2.4 on 2021-10-04 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Fundings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('status', models.BooleanField(max_length=100)),
                ('deadline', models.CharField(max_length=5000)),
                ('eligibility', models.CharField(max_length=5000)),
                ('url', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=10000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ministry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.ministry')),
            ],
        ),
    ]
